<?php

/**
 * @var \Inchoo\TicketManager\Block\NewBlock $block
 */
?>

<form class="form" action="<?php /* @escapeNotVerified */
echo $block->getPostUrl(); ?>" id="ticket-form" method="post" data-hasrequired="* Required Fields"
      data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="subject"><span>Subject</span></label>
            <div class="control">
                <input data-validate='{"required":true}' name="subject" id="subject"
                       title="<?= $block->escapeHtmlAttr(__('Subject')) ?>" value=""
                       class="input-text" type="text"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="message"><span>Message</span></label>
            <div class="control">
                <textarea data-validate='{"required":true}' name="message" id="message"
                          title="<?= $block->escapeHtmlAttr(__('Message')) ?>"
                          value="" class="input-text" type="text"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Save" class="action submit primary">
                <span>Save</span>
            </button>
        </div>
    </div>
</form>